### ISSUE TITLE
link error when building YOLOv10-OpenVINO-CPP-Inference

### ISSUE THREAD

**Issue by wilbertmatthew** [rlggyp/YOLOv10-OpenVINO-CPP-Inference#2]
I using Ubuntu 18.04 and I get the following error when trying to build YOLOv10-OpenVINO-CPP-Inference on a laptop with a builtin camera. I ran update and the install requirements.

Thanks
Wilbert Jackson

cmake ..
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wilbert/YOLOv10-OpenVINO-CPP-Inference/src/build
(base) root@wilbert-Gazelle:/home/wilbert/YOLOv10-OpenVINO-CPP-Inference/src/build# make
Consolidate compiler generated dependencies of target inference_lib
[ 33%] Built target inference_lib
Consolidate compiler generated dependencies of target camera
[ 44%] Linking CXX executable camera
/usr/bin/ld: warning: //root/anaconda3/lib/libgomp.so.1: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
/usr/bin/ld: warning: //root/anaconda3/lib/libgomp.so.1: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
/opt/intel/openvino/runtime/lib/intel64/libopenvino.so: undefined reference to `pow@GLIBC_2.29'
/opt/intel/openvino/runtime/lib/intel64/libopenvino.so: undefined reference to `exp@GLIBC_2.29'
/opt/intel/openvino/runtime/lib/intel64/libopenvino.so: undefined reference to `log@GLIBC_2.29'
collect2: error: ld returned 1 exit status
CMakeFiles/camera.dir/build.make:154: recipe for target 'camera' failed
make[2]: *** [camera] Error 1
CMakeFiles/Makefile2:114: recipe for target 'CMakeFiles/camera.dir/all' failed
make[1]: *** [CMakeFiles/camera.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2
(base) root@wilbert-Gazelle:/home/wilbert/YOLOv10-OpenVINO-CPP-Inference/src/build#

**Comment by rlggyp** [comment]
Please make sure that you already install the dependencies
```bash
sudo apt-get update && sudo apt-get install --no-install-recommends -y \
    libtbb2 \
    libyaml-cpp-dev \
    git \
    vim \
    nano \
    cmake \
    wget \
    libopencv-dev \
    pkg-config \
    g++ \
    gcc \
    libc6-dev \
    make \
    build-essential \
    sudo \
    ocl-icd-libopencl1 \
    python3 \
    python3-venv \
    python3-pip \
    libpython3.8
```

**Comment by rlggyp** [comment]
### Install OpenVINO library
```bash
wget -O openvino.tgz https://storage.openvinotoolkit.org/repositories/openvino/packages/2023.3/linux/l_openvino_toolkit_ubuntu18_2023.3.0.13775.ceeafaf64f3_x86_64.tgz && \
sudo mkdir /opt/intel
sudo mv openvino.tgz /opt/intel/
cd /opt/intel
sudo tar -xvf openvino.tgz
sudo rm openvino.tgz
sudo mv l_openvino* openvino
```

**Comment by wilbertmatthew** [comment]
Thanks for your response. I have performed these setup instructions 3 times
now and I get the same error.

Thanks

**Comment by rlggyp** [comment]
Hi @wilbertmatthew 

I appreciate you bringing this to my attention.

I recently set up Ubuntu 18.04 on a Docker container and did not encounter any errors during the build process. Have you tried using a Docker container for your setup? It can help create a consistent environment and might resolve the issues you're facing.

To assist you further, I have an image on my Docker Hub that you can use:
```sh
docker pull rlggyp/yolov10:18.04
```
If you need guidance on setting up a Docker container or using this image, I'd be happy to help.

**Comment by wilbertmatthew** [comment]
Thanks for your response. I think the issue may relate to an older version
of GLIB installed. I did ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1.6) 2.27. The error relates to not
finding GLIBC_2.29. I'll update GLIB and try.

Thanks

**Comment by rlggyp** [comment]
Hi @wilbertmatthew 

Thank you for checking the GLIBC version. It sounds like updating GLIBC to version 2.29 should resolve the issue.

Please try the update and let me know if it resolves the problem. If everything works, could you kindly close the issue? If you encounter any further problems, feel free to reopen the issue or create a new one.

Thank You 🙂.

**Comment by wilbertmatthew** [comment]
Thanks for your help. Got it working my upgrading glib.
