### ISSUE TITLE
export model onnx

### ISSUE THREAD

**Issue by vtn98** [rlggyp/YOLOv10-OpenVINO-CPP-Inference#5]
Hi @rlggyp 
Thank your project
I tried exporting the onnx model with the options: half = True or int8 = True. but it seems it is not the same as your onnx model
Can you share with me how to export the onnx model used in this project?
Thank you.

**Comment by rlggyp** [comment]
Hello @vtn98,

I exported the ONNX model using this [notebook](https://github.com/rlggyp/YOLOv10-OpenVINO-CPP-Inference/blob/main/notebooks/YOLOv10_exporter.ipynb). My ONNX model uses FP32 precision. However, I successfully converted the ONNX model into OpenVINO with different precisions (`FP32`, `FP16`, and `INT8`) using this [notebook](https://github.com/openvinotoolkit/openvino_notebooks/blob/latest/notebooks/yolov10-optimization/yolov10-optimization.ipynb).

Thank you.

**Comment by vtn98** [comment]
Thank @rlggyp 
I will try it now.

**Comment by vtn98** [comment]
Hi @rlggyp 
I tried exporting according to [notebook](https://github.com/rlggyp/YOLOv10-OpenVINO-CPP-Inference/blob/main/notebooks/YOLOv10_exporter.ipynb) link. However, it still does not produce the same model as the one I downloaded from you [onnx](https://github.com/rlggyp/YOLOv10-OpenVINO-CPP-Inference/raw/model/assets/yolov10n.onnx)
size model that I exported (yolov10n.pt): 9435950MB. The time inference about 40-50ms
size model that I downloaded from you: 9309883MB. The time inference about 18-20ms 
Please, check for me

**Comment by rlggyp** [comment]
Hello @vtn98 

![image](https://github.com/rlggyp/YOLOv10-OpenVINO-CPP-Inference/assets/76827698/4294b038-74a7-4ea1-881d-f249c2e8b000)

After discovering why the old model was fast, I realized it was exported with an input size of 320x320, which explains its quick performance. You can verify this using [netron](https://netron.app).

To export model with an input size of 320x320, use this command:
```bash
!yolo export model=yolov10n.pt format=onnx imgsz=320 simplify=True
```

**Comment by vtn98** [comment]
Thank @rlggyp 
I got it.
